config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'

  resources :jets do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create, :show]
  end
  # destroy for booking owner
  resources :booking, only: [:destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :jet
end

app/models/jet.rb
class Jet < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  mount_uploader :photo, PhotoUploader
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :jet
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :reviews
  has_many :jets, through: :bookings


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :store_user_location!, if: :storable_location?
  # The callback which stores the current location must be added before you authenticate the user
  # as `authenticate_user!` (or whatever your resource is) will halt the filter chain and redirect
  # before the location can be stored.

  private
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_jet, only: [:new, :create, :show]
  before_action :find_booking, only: [:show, :destroy]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.jet = @jet

    if @booking.save
      redirect_to jet_booking_path(@jet, @booking)
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @booking.destroy
    redirect_to jet_path(@booking.jet)
  end

  private

  def find_jet
    @jet = Jet.find(params[:jet_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :passengers, :destination, :jet_id, :user_id)
  end
end

app/controllers/jets_controller.rb
class JetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  def index
    ratings = []
    @jets = Jet.all
     @jets = Jet.where.not(latitude: nil, longitude: nil)

    @markers = @jets.map do |jet|
      {
        lng: jet.longitude,
        lat: jet.latitude
      }
    end
  end

  def show
    @jet = Jet.find(params[:id])
    @booking = Booking.new
    @jets = Jet.where.not(latitude: nil, longitude: nil)

    @markers = @jets.map do |jet|
      {
        lng: jet.longitude,
        lat: jet.latitude
      }
    end
  end

  def new
    @jet = Jet.new
  end

  def create
    @jet = Jet.new(jet_params)
    @jet.user = current_user
    if @jet.save!
      redirect_to jet_path(@jet)
    else
      render :new
    end
  end

  def edit
    @jet = Jet.find(params[:id])
  end

  def update
    @jet = Jet.find(params[:id])
    if @jet.update!(jet_params)
      redirect_to jet_path(@jet)
    else
      render :new
    end
  end

  def destroy
    @jet = Jet.find(params[:id])
    @user = @jet.user
    @jet.reviews.each { |r| r.destroy }
    @jet.bookings.each { |b| b.destroy }
    @jet.destroy
    redirect_to user_path(@user)
  end

  def jet_params
    params.require(:jet).permit(:name, :type, :city, :price_hour, :seats, :model, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_jet, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.jet = @jet
    if @review.save!
      redirect_to jet_path(@jet, @review)
    else
      render :new
    end
  end

  private

  def find_jet
    @jet = Jet.find(params[:jet_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :jet_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @bookings = @user.bookings
    @jets = Jet.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/show.html.erb
<div class="booking-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-offset-2 col-md-6 col-md-offset-3">
        <div class="card" style="background-image: url('https://images.unsplash.com/photo-1540962351504-03099e0a754b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cdc84c9290e90088f8ab78270ee1ffdf&auto=format&fit=crop&w=500&q=60');">
        </div>
      </div>
      <div class="col-xs-12 col-sm-8 col-md-offset-2 col-md-6 col-md-offset-3">
        <h3>Booking Confirmed</h1>
        <p><span class="booking-align">Jet:</span> <%= @jet.name %></p>
        <p><span class="booking-align">Dates:</span> <%= @booking.start_date %> / <%= @booking.end_date %></p>
        <p><span class="booking-align">Destination:</span> <%= @booking.destination %></p>
        <p><span class="booking-align">Passengers:</span> <%= @booking.passengers %></p>
        <%= link_to "Back to listing", jets_path %>
      </div>
    </div>
  </div>
</div>

app/views/jets/_booking_form.html.erb
<%= simple_form_for([@jet, @booking]) do |f|%>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.input :destination %>
  <%= f.input :passengers %>
  <%= f.submit class: "btn btn-danger" %>
<% end %>

app/views/jets/create.html.erb
<h1>Jets#create</h1>
<p>Find me in app/views/jets/create.html.erb</p>

app/views/jets/destroy.html.erb
<!-- <h1>Jets#destroy</h1>
<p>Find me in app/views/jets/destroy.html.erb</p>
 -->

  <h1 class="header_form">Delete your jet</h1>
<div class="col-xs-12 col-sm-6 col-sm-offset-3">
  <%= simple_form_for(@jet) do |f|%>
    <div class="row_form">
      <div class="col-xs-12 col-sm-4-offset-3">
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.input :price_hour %>
      <%= f.input :city%>
      <%= f.input :seats %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit class: "blue-button" %>

</div>
    </div>
  <% end %>
</div>

app/views/jets/edit.html.erb
<!-- <h1>Jets#edit</h1>
<p>Find me in app/views/jets/edit.html.erb</p>
 -->

 <h1 class="header_form">Change features to your jet</h1>
<div class="col-xs-12 col-sm-6 col-sm-offset-3">
  <%= simple_form_for(@jet) do |f|%>
    <div class="row_form">
      <div class="col-xs-12 col-sm-4-offset-3">
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.input :price_hour %>
      <%= f.input :city%>
      <%= f.input :seats %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit class: "blue-button" %>

</div>
    </div>
  <% end %>
</div>

app/views/jets/index.html.erb
<div class="jets-banner">
  <video id="banner_video" src="<%= image_path 'banner_video.mp4' %>" type="video/mp4" autoplay loop muted >
  </video>
  <div class="banner_button">

    <h1>Find the flight of your dreams!</h1>
    <a href="#main-container"><img src="https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_arrow_drop_down_48px-512.png" alt="" style="height: 150px"></a>

  </div>
  <div class="jets-banner-content">

  </div>
</div>
<div id="main-container">

  <div class="left">
    <div class="row">
      <% @jets.reverse.each do |jet| %>
        <div class="col-sm-6">
          <div class="index-card">
            <%= link_to jet_path(jet) do %>
              <% if jet.photo? %>
              <%= link_to jet_path(jet) do %>
                <div class="index-card-image" style="background-image: url('<%= cl_image_path jet.photo, height: 300, width: 400 %>');background-size: cover; height: 220px;">
                </div>
                <% end %>
              <% else %>
            <%= link_to jet_path(jet) do %>
              <div class="index-card-image" style="background-image: url('https://images.unsplash.com/photo-1540962351504-03099e0a754b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cdc84c9290e90088f8ab78270ee1ffdf&auto=format&fit=crop&w=450&h=300&q=60'); height: 220px;">
              </div>
              <% end %>
            <% end %>
            <% end %>
            <div class="index-card-text">
              <h3><%= jet.name %></h3>
              <h6>£<%= jet.price_hour %> per hour</h6>
              <% if jet.user == current_user %>
              <h6><em> This is your Jet!</em></h6>
              <% else %>
              <% if jet.reviews.blank? %>
                  <p>No Reviews yet!<p>
              <% else %>
                <div class="star-holder">
                  <% stars_num = ((jet.reviews.map {|e| e.rating}.sum).to_f / jet.reviews.count).round(2) %>
                  <% stars_num.to_i.times do %>
                    <i class="fas fa-star yellow"></i>
                  <% end %>
                </div>
              <% end %>
              <% end %>
            </div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
  <div class="right">
    <div
      id="map"
      style="width: 100%;
      height: 720px;"
      data-markers="<%= @markers.to_json %>">
    </div>
  </div>
</div>

app/views/jets/new.html.erb
<h1 class="header_form">Add your jet</h1>
<div class="col-xs-12 col-sm-6 col-sm-offset-3">
  <%= simple_form_for(@jet) do |f|%>
    <div class="row_form">
      <div class="col-xs-12 col-sm-4-offset-3">
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.input :price_hour %>
      <%= f.input :city%>
      <%= f.input :seats %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit class: "btn btn-danger" %>

</div>
    </div>
  <% end %>
</div>

app/views/jets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="col-xs-12 col-sm-6">
        <% if @jet.photo? %>
       <div class="card" style="background-image: url('<%= cl_image_path @jet.photo, height: 300, width: 400 %>');background-size: cover;">
      <% else %>
       <div class="card" style="background-image: url('https://images.unsplash.com/photo-1540962351504-03099e0a754b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cdc84c9290e90088f8ab78270ee1ffdf&auto=format&fit=crop&w=500&q=60');">
      <% end %>
      </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <h5><strong>Location:</strong><%= @jet.city %></h5>
        <h5><strong>Name:</strong> <%= @jet.name %></h5>
        <h5><strong>Model:</strong> <%= @jet.model %></h5>
        <h5><strong>Price:</strong> £<%= @jet.price_hour %> <em>per hour</em></h5>
        <% total = count = average = 0 %>
        <% @jet.reviews.each do| review| %>
          <% total += review.rating %>
          <% count += 1 %>
        <% end %>
        <% average = count == 0 ? 0 : total / count %>
        Rating: <% average.times do %>
        <i class="fas fa-star yellow"></i>
      <% end %>
      <% if @jet.user == current_user %>
      <h4> This is your Jet!</h4>
      <i class="fas fa-plane"></i>
      <%= link_to 'Go Back to Listings', jets_path %>
      <% end %>
    </div>
    </div>
    <div class="col-xs-12 col-sm-6">
    <br>
        <p class="tagline"><strong>What the name promises, the plane delivers</strong></p>
        <p>This model redefines what's possible in a private jet. Its range, speed and reliability are amongst the best available, while its cabin offers comfort and amenities no matter what the weather outside. This light cabin class private jet is designed to land safely at the smallest airports, meaning that remote island or mountain destinations are always within reach.</p>
        <p>The perfect choice for business or leisure to international destinations within a few hours away. Fast and comfortable with seating up to ten passengers, available with as little as a twelve hour notice. Included in this fine aircraft are snacks stocked to your taste, signature series inflight dining, always available with your favourite drinks as well as precise cabin temperature control. With the seats facing each other, the layout of the jet is designed for perfect conversation as well as generous luggage capacity.</p>
    <br>
            <i class="fas fa-plane"></i>
    <%= link_to 'Go Back to Listings', jets_path %>
    </div>
    <% if @jet.user != current_user %>
  <div class="col-xs-12 col-sm-6">
    <%= render "booking_form" %>
  </div>
  <% else %>
  <div class="col-xs-12 col-sm-6">
  <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>">
  </div>
  </div>
  <% end %>
  </div>
</div>
</div>

app/views/jets/update.html.erb
<h1>Jets#update</h1>
<p>Find me in app/views/jets/update.html.erb</p>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "rentajet_logo_dark.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to 'Rent a jet', jets_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to 'Rent your jet', new_jet_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "Dashboard", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "avatar_placeholder.png", class: "avatar", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to jets_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <a href="" class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#modal-login">Log in</a>
      <a href="" class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#modal-signup">Sign up</a>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_user_modals.html.erb
<!-- Login Modal -->
<div class="modal fade" id="modal-login" tabindex="-1" role="dialog" aria-labelledby="modal-login-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-login-title">Log in</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(:user, :url => session_path(:user)) do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %> <br />
          <%= link_to "Forgot your password?", new_password_path(:user), class: "modal-link" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <%= f.submit 'Sign in', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Signup Modal -->
<div class="modal fade" id="modal-signup" tabindex="-1" role="dialog" aria-labelledby="modal-signup-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-signup-title">SignUp</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <%= f.submit "Sign up", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-banner">
  <div class="home-nav">
    <%= image_tag "rentajet_logo_light.png" %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to 'Rent a jet', jets_path, class: "anchor-shadow" %>
      <%= link_to 'Rent your jet', new_jet_path, class: "anchor-shadow" %>
      <%= link_to "Dashboard", user_path(current_user), class: "anchor-shadow" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item home-item">
        <div class="dropdown">
          <%= image_tag "avatar_placeholder.png", class: "home-avatar", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <!-- <%= link_to t(".sign_in", default: "Log in"), new_user_session_path %> -->
      <a href="" data-toggle="modal" data-target="#modal-login">Log in</a>
      <!-- <%= link_to "Sign up", "/users/sign_up" %> -->
      <a href="" data-toggle="modal" data-target="#modal-signup">Sign up</a>
    <% end %>
    </div>
  </div>

  <div class="home-search">
    <%= form_tag jets_path, method: :get do |f| %>
      <div id="home-from">
        <label for="origin">From</label>
        <!-- <input type="text" placeholder="origin" /> -->
        <%= text_field_tag :city, params[:city], placeholder: "origin" %>
      </div>
      <div id="home-to">
        <label for="">To</label>
        <!-- <input type="text" placeholder="destination" /> -->
        <%= text_field_tag :destination, params[:destination], placeholder: "destination" %>
      </div>
      <div id="home-depart">
        <label for="">Depart</label>
        <!-- <input type="text" placeholder="depart" /> -->
        <%= text_field_tag :start_date, params[:start_date], placeholder: "departure" %>
      </div>
      <div id="home-return">
        <label for="">Return</label>
        <!-- <input type="text" placeholder="return" /> -->
        <%= text_field_tag :end_date, params[:end_date], placeholder: "return" %>
      </div>
      <div id="home-passengers">
        <label for="">Passengers</label>
        <!-- <input type="text" placeholder="passengers" /> -->
        <%= text_field_tag :seats, params[:seats], placeholder: "passengers" %>
      </div>
      <div id="home-submit">
        <label for="">&nbsp;</label>
        <button type="submit" class="home-submit">
          <i class="fas fa-search"></i> Search
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/users/show.html.erb
<div class="tab">
  <button class="tablinks" onclick="openCity(event, 'Bookings')">My Bookings</button>
  <button class="tablinks" onclick="openCity(event, 'Jets')">My Jets</button>
</div>

<div id="My Bookings" class="tabcontent">
  <h3></h3>
  <p>.</p>
</div>



<div id="Bookings" class="tickets tabcontent">
  <% @bookings.each do |booking| %>
  <div class="ticket">
    <div class="stub">
      <div class="top">
        <%= image_tag "rentajet_logo_dark.png", class: "booking-logo" %>
        <span class="line"></span>
        <span class="num">
          Booking-Nr
          <span>31415926</span>
        </span>
      </div>
      <div class="number">1</div>
      <div class="invite">
        Boarding Pass
      </div>
    </div>
    <div class="check">
      <div class="route">
        <span class="big"><%= booking.jet.city %></span>
        <span class="plane"><?xml version="1.0" ?><svg clip-rule="evenodd" fill-rule="evenodd" height="60" width="60" image-rendering="optimizeQuality" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg"><g stroke="#222"><line fill="none" stroke-linecap="round" stroke-width="30" x1="300" x2="55" y1="390" y2="390"/><path d="M98 325c-9 10 10 16 25 6l311-156c24-17 35-25 42-50 2-15-46-11-78-7-15 1-34 10-42 16l-56 35 1-1-169-31c-14-3-24-5-37-1-10 5-18 10-27 18l122 72c4 3 5 7 1 9l-44 27-75-15c-10-2-18-4-28 0-8 4-14 9-20 15l74 63z" fill="#222" stroke-linejoin="round" stroke-width="10"/></g></svg></span>
        <span class="big"><%= booking.destination.capitalize %></span>
      </div>
      <div class="number">Seat: <%= (0..booking.jet.seats-1).to_a.sample+1%> <%= %w(A B C D E F).sample %>
        </%></div>
        <div class="info">
          <section>
            <div class="title">Date</div>
            <div><%= booking.created_at %></div>
          </section>
          <section>
            <div class="title">Issued By</div>
            <div>Rent-A-Jet</div>
          </section>
          <section>
            <div class="title">Booking Nr</div>
            <div>31415926</div>
          </section>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<div id="Jets" class="container tabcontent">
  <% @jets.each do |jet| %>
    <h5>Name of Jet: <%= jet.name %></h5>
    <h5>Model: <%= jet.model %></h5>
    <h5>Price per hour: <%= jet.price_hour %></h5>
    <h5>City: <%= jet.city %></h5>
    <div class="edit-remove-button">
      <%= link_to "Edit", edit_jet_path(jet) %> |

      <%= link_to "Remove", jet_path(jet), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
    <% if jet.photo? %>
      <div class="card" style="background-image: url('<%= cl_image_path jet.photo, height: 300, width: 400 %>');background-size: cover;">
      </div>
    <% else %>
      <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(60,60,60,0.6) 50%), url('https://images.unsplash.com/photo-1540962351504-03099e0a754b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cdc84c9290e90088f8ab78270ee1ffdf&auto=format&fit=crop&w=500&q=60');">
      </div>
    <% end %>
  <% end %>
  </div>
</div>

<script>
  function openCity(evt, cityName) {
    // Declare all variables
    var i, tabcontent, tablinks;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the button that opened the tab
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
  }


</script>